ignorePatterns:
  - "www"
  - "**/dist/*"
  - "*.cjs"
  - "**/node_modules/*"
env:
  node: true
  browser: true
  es6: true
  jest: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:react/jsx-runtime"
  - "prettier"
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
parser: "@typescript-eslint/parser"
parserOptions:
  project:
    - "./packages/*/tsconfig.json"
    - "./tsconfig.base.json"
  tsconfigRootDir: "./"
plugins:
  - "@typescript-eslint"
  - import
  - "prettier"
settings:
  import/resolver:
    typescript: {}
  react:
    version: detect
rules:
  '@typescript-eslint/unbound-method': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-unsafe-assignment': off
  '@typescript-eslint/no-unsafe-member-access': off
  '@typescript-eslint/no-unsafe-call': off
  '@typescript-eslint/no-unsafe-return': off
  quotes:
    - error
    - single
    - avoidEscape: true
  prettier/prettier:
    - error
    - trailingComma: "all"
      singleQuote: true
      printWidth: 100
      endOfLine: "auto"
      semi: true
  react/prop-types:
    - 0
  react/no-unescaped-entities:
    - 0

